---
- hosts: '{{ nodes }}'
  vars:
    ros2_user:
      name: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
    ros2_workspace: '/home/{{ ros2_user.name }}/{{ ros2_distribution }}_ws/'



  tasks:

  - name: lookup desired ros config
    ansible.builtin.include_vars:
      file: vars/ros-config.yml

  - name: lookup desired workspace layout
    ansible.builtin.include_vars:
      file: vars/workspace-config.yml

  - name: report the config back
    ansible.builtin.debug:
      msg: 
        - 'Managing ROS2 {{ ros2_distribution }}'
        - 'for user: {{ ros2_user.name }}'
        - 'in workspace at {{ ros2_workspace }}'
        #- 'preloading directories with config {{ ros2_workspace_layout }}'


  ############## start changing the target #################

  # XXX offer a way of removing packages from a workspace

  - name: ROS2 remove existing build files
    include: tasks/ros2-clean-workspace.yml
    when: (fullclean|bool)

  - name: ROS2 remove sources
    include: tasks/ros2-erase-workspace.yml
    when: (remove_sources|bool) and (ws_dirs is defined)




