---
# fetch package-specific system dependencies

# XXX rosdep wants apt to fetch rti-connext-dds-5.3.1
#     which is not available in the normal repos.
#     this is what we need the OSRF repos for.

# update rosdep package lists
- name: rosdep update package lists
  command: rosdep update
  args:
    chdir: '{{ ros2_workspace }}'

# use rosdep to download package dependencies
- name: rosdep install system dependencies
  command: rosdep install --from-paths src/ --ignore-src -r -y
  become: yes
  args:
    chdir: '{{ ros2_workspace }}'



