---
# build with colcon using defaults set previously


# my sympathies to your SD card
- name: ROS2 Colcon | add swap space for build
  include: ros2-colcon-extra-swap-enable.yml
  vars:
    swap_file_path: '{{ ros2_workspace }}/colcon_swapfile'
    swap_file_size_mib: '4096'
  when: (ros2_colcon_use_swap|default(false))|bool

# XXX take a variable for the sub directory to rebuild

- name: ROS2 Colcon | build
  shell: >
    {% if ros2_colcon_single_core|default(false) %}
    MAKEFLAGS="-j1"
    {% endif %}
    colcon build
    {% if ros2_colcon_skip_packages_to is defined %}
    --packages-skip-up-to {{ ros2_colcon_skip_packages_to }}
    {% endif %}
  args:
    chdir: '{{ ros2_workspace }}'


- name: ROS2 Colcon | remove swap space
  include: ros2-colcon-extra-swap-disable.yml
  vars:
    swap_file_path: '{{ ros2_workspace }}/colcon_swapfile'
  when: (ros2_colcon_use_swap|default(false))|bool
