---
# build with colcon using defaults set previously
# XXX defaults should include --symlink-install

- name: Build the workspace with colon
  command: colcon build 
  args:
    chdir: '{{ ros2_workspace }}'
