---

# --deps
# --deps-up-to {{ deps_up_to }}

# using rosinstall_generator.
# Instead of fiddling with --deps-up-to and tracking which packages were listed prior,
#     we can use --exclude-path src.
# This unfortunately requires us to both list and download on each step

# use rosinstall_generator to list packages to download
- name: rosinstall_generator create a list of source locations for ros packages
  ansible.builtin.shell: 'rosinstall_generator {{ packages }} --rosdistro {{ ros2_distribution }} --deps --exclude-path src > {{ vcs_name }}.repos'
  args:
    executable: /bin/bash
    chdir: {{ ros2_workspace }}
    #creates: {{ vcs_name }}.repos  # allow update


# use vcs_tool to download packages
- name: vcs_tool download the sources listed by rosinstall_generator
  ansible.builtin.shell: 'vcs-import src/{{ target_ws_dir }} < {{ vcs_name }}.repos'
  args:
    executable: /bin/bash
    chdir: '{{ ros2_workspace }}'




