---

# --deps
# --deps-up-to {{ deps_up_to }}

# using rosinstall_generator.
# Instead of fiddling with --deps-up-to and tracking which packages were listed prior,
#     we can use --exclude-path src.
# This unfortunately requires us to both list and download on each step

# use rosinstall_generator to list packages to download
- name: ROS2 list sources using rosinstall_generator
  shell: 'rosinstall_generator {{ ros_packages|join(" ") }} --rosdistro {{ ros2_distribution }} --deps --exclude-path src > {{ target_ws_dir }}.repos'
  args:
    executable: /bin/bash
    chdir: '{{ ros2_workspace }}'
    creates: '{{ target_ws_dir }}.repos'  # XXX allow update
  #when: ros_packages is defined and ros_packages is not empty

# use vcs_tool to download packages
- name: ROS2 download sources with vcs_tool
  shell: 'vcs-import src/{{ target_ws_dir }} < {{ target_ws_dir }}.repos'
  args:
    executable: /bin/bash
    chdir: '{{ ros2_workspace }}'
  #when: ros_packages is defined and ros_packages is not empty




