---
# pick your ROS2 flavour (only galactic has been tested)
ros2_distribution: galactic

# if you're running your own apt mirrors, this is where you want to set those
ros2_gpg_key_url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
ros2_repository_url: http://packages.ros.org/ros2/ubuntu

