---


# automatically prepare a source-only workspace with a mix of vcs and git repos
# 
#
# git repos are placed into folders accoring to:
#   ws/src/{{ target_ws_dir }}/{{ git_repos[n].dest }}
#
# vcs trees are placed under 
#   ws/src/{{ target_ws_dir }}/< vcs tree goes here>
#
# vcs repo names are generated as
#   {{ target_ws_dir }}.repos

ros2_workspace_layout:
  # this is needed on 32b arm and unsupported platforms
  # XXX add an install-from-binary option
  - target_ws_dir: core
    ros_packages:
      - ros_core
    git_repos: []

  # this demonstrates adding native ROS features beyond ros_core
  # these packages can also normally come from apt except for 32b
  - target_ws_dir: teleop
    ros_packages:
      - joy
      - sdl2_vendor
      - joy_linux
      - diagnostic_updater
      - teleop_twist_keyboard
      - teleop_twist_joy
    git_repos: []

  # a placeholder to demonstrate loading your own git repos
  - target_ws_dir: sound_app
    ros_packages: []
    git_repos:
      - dest: ros-gst-bridge  # allow name override
        repo: 'https://github.com/BrettRD/ros-gst-bridge.git'
        # version: HEAD # XXX fiddle with conditionals
      - dest: monitoring  # allow name override
        repo: 'https://github.com/BrettRD/ros2_monitor.git'
  # XXX add support for vcs .repos files